const products = [
    {
        '_id': '1',
        'name': 'MOTUL 5W-30 5L',
        'image': '/img/motul.jpg',
        'description': 'Высокотехнологичное 100% синтетическое моторное масло, специально разработано для мощных и современных автомобилей.',
        'brand': 'Motule',
        'category': 'Oil',
        'price': 2233,
        'countInStock': 10,
        'rating': 4.5,
    },

    {
        '_id': '2',
        'name': 'GM Air Filter',
        'image': '/img/air_filter.jpg',
        'description': 'General Motors Повітряний фільтр',
        'brand': 'General Motors',
        'category': 'filters',
        'price': 176,
        'countInStock': 0,
        'rating': 2.0,
    },

    {
        '_id': '3',
        'name': 'W 811/80 Mann Оливний фільтр',
        'image': '/img/mann_oil_filter.jpg',
        'description': 'Оливний фільтр Mann W 811/80 – накручуваний фільтр для моторної оливи, призначений для автомобілів марок Форд, Хюндай, Фіат, Грейт Уолл, Кіа, Опель, Субару і багатьох інших марок – як легкових, так і комерційних.',
        'brand': 'Mann',
        'category': 'filters',
        'price': 265,
        'countInStock': 15,
        'rating': 4.1,
    },
    {
        '_id': '4',
        'name': 'C2W001ABE Abe Гальмівні колодки',
        'image': '/img/abe_break.jpg',
        'description': 'БЕ C2W001ABE – високоякісні гальмові колодки, призначені для заднього моста, сумісні з гальмівними системами Сітроен, Ауді, Пежо, Форд, Рено, Шкода, Фольксваген. Даний продукт призначений для дискових систем гальмування.',
        'brand': 'ABE',
        'category': 'break systems',
        'price': 580,
        'countInStock': 7,
        'rating': 4.2,
    },
    {
        '_id': '5',
        'name': 'DF2803 TRW Гальмівний диск',
        'image': '/img/trw_break.jpg',
        'description': 'TRW Гальмівний диск',
        'brand': 'TRW',
        'category': 'break systems',
        'price': 1287,
        'countInStock': 6,
        'rating': 3.0,
    },
    {
        '_id': '6',
        'name': 'Акумулятор Bosch 6 CT-74-R S5 Silver Plus 0092S50070',
        'image': '/img/akum_bosch.jpg',
        'description': 'Акумулятор Bosch 6 СТ-74-R S5 Silver Plus 0092S50070 – представлений в серії Bosch S5 Silver Plus, розроблений і призначений для використання в автомобілях бізнес-класу.',
        'brand': 'Bosch',
        'category': 'electricity',
        'price': 3795,
        'countInStock': 4,
        'rating': 4.6,
    },
]

export default products
